# Generated by Django 5.0 on 2023-12-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='johan_app/static/img/')),
            ],
        ),
    ]
