# Generated by Django 5.0 on 2023-12-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
