# Generated by Django 5.0 on 2023-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1_app', '0002_product_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Johan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
            ],
        ),
    ]
